allowBuilds:
  core-js: true
  esbuild: true
overrides:
  brace-expansion@>= 3.0.0, < 5.0.7: '>=5.0.7'
  js-yaml@4.3.0: '>=3.0.3'
  esbuild@>= 0.27.3, < 0.28.1: '>=0.28.1'
  micromatch@<4.0.8: '>=4.0.8'
