import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Get __dirname in ES module context
const __dirname = dirname(fileURLToPath(import.meta.url));

// Read package.json
const pkgPath = join(__dirname, '../package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));

// Prepare version.ts content
const versionTs = `// This file is auto-generated by scripts/generate-version.ts
export const version = "${pkg.version}";
`;

// Write to src/version.ts
const outPath = join(__dirname, '../src/version.ts');
writeFileSync(outPath, versionTs, { encoding: 'utf8' });

console.log(`Generated src/version.ts with version ${pkg.version}`);
